#!/bin/bash
################################################################################
# (c) Copyright 2007-2015 Alces Software Ltd & Stephen F Norledge.             #
#                                                                              #
# Storage Manager Daemon                                                       #
#                                                                              #
# This file/package is part of the Storage Manager Daemon.                     #
#                                                                              #
# This is free software: you can redistribute it and/or modify it under        #
# the terms of the GNU Affero General Public License as published by the Free  #
# Software Foundation, either version 3 of the License, or (at your option)    #
# any later version.                                                           #
#                                                                              #
# This file is distributed in the hope that it will be useful, but WITHOUT     #
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or        #
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License #
# for more details.                                                            #
#                                                                              #
# You should have received a copy of the GNU Affero General Public License     #
# along with this product.  If not, see <http://www.gnu.org/licenses/>.        #
#                                                                              #
# For more information on Alces Software, please visit:                        #
# http://www.alces-software.org/                                               #
#                                                                              #
################################################################################
# chkconfig: 2345 91 01
# alces-storage-manager-daemon: start/stop alces storage-manager-daemon
# description: start/stop alces storage-manager-daemon
#
. /etc/rc.d/init.d/functions

# For accessing qstat etc.
if [ -f /etc/profile.d/ge.sh ]; then
  . /etc/profile.d/ge.sh
fi

export RUBY_HOME=/opt/alces/ruby
export PATH=/opt/alces/ruby/bin:$PATH
export LD_LIBRARY_PATH=/opt/alces/ruby/lib:$LD_LIBRARY_PATH

PID_FILE=/var/run/alces-storage-manager-daemon.pid
DAEMON_HOME=/opt/alces/alces-storage-manager-daemon
DAEMON_CMD="$DAEMON_HOME/bin/alces-storage-manager-daemon start --pidfile $PID_FILE -e production"
START_LOG=/var/log/alces-storage-manager-daemon-init.log

start()
{
  echo -n Starting Alces Storage Manager daemon:
  cd $DAEMON_HOME
  $DAEMON_CMD &> $START_LOG
  sleep 2
  PID=`pidofproc -p $PID_FILE`
  if [ -n $PID ]; then
    if checkpid $PID; then 
        touch /var/lock/subsys/alces-storage-manager-daemon
        success
        RETVAL=0
    else
        rm -f $PID_FILE
        failure
        RETVAL=1
    fi
  else
    failure
    RETVAL=1
  fi
  echo 
}

restart()
{
  echo -n Restarting Alces Storage Manager daemon:
  PID=`pidofproc -p $PID_FILE`
  kill $PID
  sleep 1
  cd $DAEMON_HOME
  $DAEMON_CMD &> $START_LOG
  PID=`pidofproc -p $PID_FILE`
  if [ -n $PID ]; then
    if checkpid $PID; then 
        success
        RETVAL=0
    else
        rm -f $PID_FILE
        failure
        RETVAL=1
    fi
  else
    failure
    RETVAL=1
  fi

  echo 
}

stop()
{
  echo -n "Stopping Alces Storage Manager daemon:"
  PID=`pidofproc -p $PID_FILE`
  kill $PID
  sleep 1
  if checkpid $PID; then
      failure
      RETVAL=1
  else
      rm -f /var/lock/subsys/alces-storage-manager-daemon
      rm -f $PID_FILE
      success
      RETVAL=0
  fi

  echo
}

running()
{
  test -f $PID_FILE
}
case "$1" in
  start)
    running && echo Already started! || start
  ;;
  stop)
    running && stop || echo Not yet started!
  ;;
  restart)
    restart
  ;;
  status)
    running && echo "RUNNING" || (echo "NOT STARTED"; exit 3)
  ;;
  *)
    echo "Usage: $0 {start|stop|restart|status}"
esac 

exit $RETVAL
